lsst-ts/LOVE-manager

- manager/subscription/consumers.py
- manager/subscription/tests/test_commands.py
- manager/subscription/tests/test_subscriptions.py
Add subscription parameter to subscription data
> Add subscription parameter to subscription data

- manager/api/serializers.py
- manager/api/tests/tests_auth_api.py
- manager/requirements.txt
> Send tai to utc difference (in secs) when serializing the Token)

- manager/subscription/consumers.py
- manager/subscription/tests/test_subscriptions.py
> Initial_state subscription request

- manager/runserver-dev.sh
- manager/runserver.sh
- manager/ui_framework/fixtures/initial_data.json
- manager/ui_framework/views.py
* Add View fixtures
* Add search endpoint for Views
* Update default sort order
> UIF fixtures

- manager/api/schema_validator.py
- manager/api/tests/test_schema_validation.py
- manager/api/urls.py
- manager/api/views.py
- manager/manager/urls.py
- manager/requirements.txt
Copying this validator: https://github.com/lsst-ts/ts_salobj/blob/2511d2ae0318c662d6351949c5b7f37a97f3f389/python/lsst/ts/salobj/validator.py
> Endpoint for script config-schema validation

- manager/subscription/consumers.py
- manager/subscription/tests/test_lovecsc_subscriptions.py
- manager/subscription/tests/test_subscriptions.py
Adds a test to ensure that observing logs are processed correctly
> Observing logs

- Dockerfile
- Dockerfile-dev
- manager/subscription/consumers.py
- manager/subscription/tests/test_heartbeat.py
Add independent heartbeat to every client, every 3 seconds
> Manager heartbeat

- manager/subscription/consumers.py
- manager/subscription/heartbeat_manager.py
- manager/subscription/tests/test_heartbeat.py
Add functionality for sending and receiving generic heartbeats
> Love hearbeats

- manager/manager/settings.py
- Remove unused values from `ALLOWED_HOSTS`
- Add content of environment variable `SERVER_ULR` (if it exists) to `ALLOWED_HOSTS`
> Change Allowed Hosts to receive external env var

- manager/ui_framework/fixtures/initial_data.json
Change configuration to store category, changing `ATDome-0-position` to `telemetry-ATDome-0-position`
> Update Health Status Summary fixture

- Jenkinsfile
- manager/manager/settings.py
- manager/requirements.txt
- manager/subscription/auth.py
- manager/subscription/heartbeat_manager.py
- manager/subscription/routing.py
This PR makes some changes related to improve the performance of the LOVE application deployed on the summit:
- Previous DJANGO_CHANNELS change was rolled back as the issue related to this was in part resolved
- Django Channels related dependencies were updated to use the most stable code
- Jenkinsfile was edited to include tickets/ branches deployment
> Support summit activities

- manager/subscription/consumers.py
This PR removes a deprecated functionality which was used for the LOVE-producer legacy version
> Remove deprecated heartbeat function

- manager/api/urls.py
- manager/api/views.py
This PR adds a new enpoint to query the EFD client instances to the commander.
> Add endpoint to list EFD client instances

- manager/subscription/heartbeat_manager.py
This micro PR removes an unnecessary print to facilitate the debugging of the system.
> Remove unnecessary print

- docker/Dockerfile-tasks
- manager/api/tests/test_authlist.py
- manager/api/views.py
- manager/manager/settings.py
- manager/requirements.txt
- manager/runserver-dev.sh
- manager/runtasks.sh
This PR makes some adjustments on the backend of the Authlist.
> Authlist adjustments

- manager/api/urls.py
- manager/api/views.py
User swap feature was missing its extension with the LDAP feature. Besides that a small code refactor was added.
> Extend and refactor LDAP login methods

- manager/ui_framework/fixtures/initial_data_base.json
Forgot to fix this the first time. Sorry.
> Fix view header for LSSTCam.

- docsrc/source/modules/how_to_use_it.rst
This PR adjusts some deprecated values for the Generic Camera configurations.
> Update docs: LOVE Config file

- CHANGELOG.rst
- manager/manager/settings.py
- manager/subscription/heartbeat_manager.py
- manager/subscription/tests/test_heartbeat.py
This PR add configuration for the checking of the heartbeat to commander with a variable of environment HEARTBEAT_QUERY_COMMANDED
> Extend Manager to receive configuration for querying  Commander

- CHANGELOG.rst
- docker/docker-compose.yml
- manager/api/tests/test_jira.py
- manager/api/tests/test_lfa.py
- manager/api/urls.py
- manager/api/views.py
- manager/manager/utils.py
This PR extends the `NarrativelogViewSet` to implement new fields that will be attached to messages: `components`, `primary_software_components` and `primary_hardware_components`.
> Extend OLE narrativelog view to implement new jira fields

- CHANGELOG.rst
- manager/manager/utils.py
This PR adjusts the payload to be sent to the Jira API so that custom fields are correctly set.
> Adjust jira ticket creation payload for custom fields

- CHANGELOG.rst
- manager/api/views.py
add a validation of the config with schema yml in ScriptConfigurationViewSet
> Possibly malformed YAML in script dialog causes crash loop on subsequent use

- CHANGELOG.rst
- manager/api/fixtures/initial_data_base.json
- manager/api/fixtures/initial_data_remote_base.json
This PR adds missing `base` fixtures for the base-teststand.
> Add missing base fixtures

- CHANGELOG.rst
- manager/api/serializers.py
- manager/api/tests/test_auth_api.py
- manager/api/tests/test_ole.py
- manager/api/urls.py
- manager/api/views.py
- manager/manager/utils.py
This PR implements the Night Report feature in order to connect the LOVE-frontend and the nightreport REST API.
> Add Night Report implementation

- CHANGELOG.rst
- README.md
This PR adds missing details about the `Channels Layer` configurations to the `README.md` file.
> Add details about Channels Layer configurations to README.
