- manager/ui_framework/serializers.py
https://github.com/lsst-ts/LOVE-manager/blob/211dbc8a46a4517196487fc3d44874cf3a2a9bbd/manager/ui_framework/serializers.py#L40
This line assumes the request comes with the `id` key which is true when editing existing views but not for new ones. This is corrected now by assigning the `max(id)+1` value or `1` if no views exist in the database.
> Base64ImageField - naive view_id extraction in file_name 

- docsrc/source/modules/how_to_use_it.rst
- manager/api/tests/test_lovecsc.py
- manager/api/urls.py
- manager/api/views.py
This PR makes a refactor to the LOVE-manager in order to send observing logs from LOVE-frontend using HTTP connection instead of websocket connections.
> Lovecsc http refactor

- Dockerfile-static
This PR add a new Dockerfile for serving LOVE-manager static files. The folders with static files are:
- `/usr/usr/love/manager/static`
- `usr/src/love/manager/media`
Now the image doesn't run the server, collect static files and only mounts the related volumes.
> Add new Dockerfile for only serving static files

- manager/manager/settings.py
- manager/subscription/consumers.py
The new version of the LOVE-producer doesn't work properly with the Script CSC, as it uses dynamic salindexes. As the CSCSummary component works with specific CSC:salindex, this event logMessages is not received because there doesn't exists a LOVE-producer container for that specific CSC:salindex. This PR makes the necessary refactor.
> Script logMessages is not compatible with the new Producer version

- README.md
- manager/manager/settings.py
- manager/subscription/consumers.py
As the LOVE-producer has two ways to being executed (using the CSC client or not). We had to document the necessary configuration to deploy each of the instances. As the LOVE-manager connects with the LOVE-producer it also has to include this configuration.
> Document LOVE-producer configuration

- manager/subscription/routing.py
This minor update allows us to scale the manager horizontally, spinning up multiple managers to deal with the traffic from one or more producers. I will file a ticket to LOVE-integration-tools with the updates for horizontal scaling. I tested this at the summit and it seems to work really well.
> Allow manager to route traffic to different manager instances.

- manager/requirements.txt
- manager/requirements_no_version.txt
This PR is a fix of the previous PR as it removed the Pillow library. At beginning we thought this library was not used, but is part of the Django database module. As it is neccesary we added it again with the respective version upgrade.
>  Bump pillow from 8.3.2 to 9.0.0 in /manager #136 

- .gitignore
- Jenkinsfile
- docker/.dockerignore
- manager/requirements.txt
- manager/ui_framework/tests/tests_models.py
This PR upgrades the astropy library to use version `5.0.3`. There were some errors because of the outdated astropy `4.0`, with the upgrade the errors disappeared.
> Upgrade to astropy 5.0.3

- manager/manager/utils.py
This PR adds a new time to the `get_times()` function to show the Observing Day of the survey.
> Add Observing Day time

- manager/api/tests/test_authlist.py
- manager/api/views.py
This PR refactors the code to connect to the Authorize CSC using the LOVE-commander endpoint for commands. Now the LOVE-manager will send the `requestAuthorization` command to the Authorize CSC for any accepted authorization request.
> Refactor Authorize CSC connection

- manager/api/tests/tests_auth_api.py
- manager/api/urls.py
- manager/api/views.py
- manager/manager/settings.py
- manager/requirements.txt
This PR contains all the implementation that refers to the LDAP integration with LOVE.
> LDAP Implementation

- manager/requirements.txt
This PR makes some upgrades to pytest libraries in order to solve security issues regarding the following alert: https://github.com/lsst-ts/LOVE-manager/security/dependabot/14.
> Upgrade pytest dependencies

- manager/requirements.txt
> Remove py library as it is not used anymore after pytest upgrade

- .pre-commit-config.yaml
- manager/api/admin.py
- manager/api/management/commands/createusers.py
- manager/api/management/commands/tests.py
- manager/api/tests/test_auth_api.py
- manager/api/tests/test_configfile.py
- manager/api/tests/test_emergencycontact.py
- manager/api/views.py
Permissions to add, edit or delete views from LOVE were given only for the admin user. This PR adds a new group of permissions with respect to the UI Framework access. Now users cmd_user, test and authlist_user have the described permissions.
Also users who login with IPA credentials and belongs to the love_ops group, will also be part of this group of permissions.
Also `black`and `flake8` versions of pre-commit hook were updated.
> Extend UI Framework permissions to normal users

- manager/manager/settings.py
This PR removes a configuration of the `channel-redis` in order to remove the encryption layer which is generating some erros at the production servers.
> Remove encryption layer for channels-redis

- manager/api/fixtures/initial_data_remote_inria.json
- manager/api/tests/test_configfile.py
- manager/api/views.py
- manager/manager/utils.py
This PR is a hotfix for LOVE-manager version 5.11.1. On the latest release a bug was introduced which produced problems to read stored configuration files. The solution was to avoid file closing on the `open` method of the new `RemoteStorage` class.
> Fix file handling on RemoteStorage class

- .github/workflows/changelog.yml
- CHANGELOG.rst
This PR adds configuration for the [Changelog checker](https://github.com/marketplace/actions/changelog-checker) github action.
> Add changelog checker github action

- CHANGELOG.rst
- README.md
- manager/api/fixtures/initial_data_remote_tucson.json
- manager/manager/settings.py
- manager/manager/urls.py
- manager/manager/utils.py
- manager/runserver.sh
- manager/subscription/routing.py
- manager/ui_framework/tests/tests_view_thumbnail.py
This PR refactors the routing system of the LOVE-manager in order to allow serving the app from a sub path (e.g. /love).
> Extend LOVE manager routing system for subpath app serving

- CHANGELOG.rst
- manager/api/models.py
This PR adds a string representation for the `ScriptConfiguration` model in order to allow easier human recognition on the admin platform.
> Add string representation for ScriptConfiguration model

- CHANGELOG.rst
- docker/docker-compose.yml
- manager/api/tests/test_lfa.py
- manager/api/views.py
This PR extends the OLE views in order to allow multiple file upload on the `create` and `update` methods of the `NarrativeLogViewSet` and `ExposureLogViewSet`.
> Extend OLE views to allow multiple file upload

- CHANGELOG.rst
- manager/api/tests/test_jira.py
- manager/manager/utils.py
This PR parses the `date_begin` and `date_end` parameters of the narrative log requests to remove the miliseconds part of the datetime string.
> Reduce miliseconds part of time of incident timestamps

- CHANGELOG.rst
- manager/api/tests/test_jira.py
- manager/manager/utils.py
This PR removes the ids mapping of the JIRA fields in order to keep that in one single place, the LOVE-frontend (check [PR#547](https://github.com/lsst-ts/LOVE-frontend/pull/547)).
> Remove JIRA fields ids mapping

- CHANGELOG.rst
- manager/ui_framework/fixtures/initial_data_base.json
- manager/ui_framework/fixtures/initial_data_inria.json
- manager/ui_framework/fixtures/initial_data_summit.json
- manager/ui_framework/fixtures/initial_data_tucson.json
This PR adjusts fixture fields to adjust the `WeatherStation` salindex so the change is persisted.
> Update WeatherStation component salindex on UI Framework fixtures

- CHANGELOG.rst
- manager/manager/settings.py
- manager/manager/utils.py
- manager/requirements.txt
- manager/runserver.sh
This PR changes a couple configurations on the LOVE-manager service:
- Replace `daphne` per `uvicorn` a lightweight fast python ASGI server as it reduces memory use considerably.
- Set `group_expiry` channels_redis configuration to big limit so no initial_state channels are being erased for non activity. See [DM-41728](https://jira.lsstcorp.org/browse/DM-41728).
Also the remote storage feature was fixed.
> Manager performance improvements

- CHANGELOG.rst
- manager/manager/settings.py
This PR sets the `FILE_UPLOAD_MAX_MEMORY_SIZE` setting to 5242880, i.e 5MB. This users will be allowed to upload files up to that limit.
> Increase users uploads max file size

- CHANGELOG.rst
- manager/api/urls.py
- manager/api/views.py
This PR adds the `reports/m1m3-bump-tests` endpoint in order to query the new app of the LOVE-commander: https://github.com/lsst-ts/LOVE-commander/pull/66.
Also several `pre-commit` warnings were fixed.
> Add M1M3 bump tests reports endpoint

- CHANGELOG.rst
- manager/api/tests/test_jira.py
- manager/api/tests/test_ole.py
- manager/api/views.py
- manager/manager/utils.py
This PR extends the `NarrativelogViewSet` and `ExposurelogViewSet` to allow JIRA ticket attachment on the `update` method.
Related to https://github.com/lsst-ts/LOVE-frontend/pull/604.
> Extend OLE update methods to allow JIRA ticket attachment

- CHANGELOG.rst
- manager/api/tests/test_jira.py
- manager/manager/utils.py
This PR makes a few adjustments to the `jira_ticket` and `jira_comment` functions in order to comply with the new parameters needed for the JIRA cloud service migration.
> Adjustments for the JIRA Cloud REST API interface

- CHANGELOG.rst
- manager/manager/utils.py
This PR updates the Jira OBS project id due to a change on the recent migration to the cloud. The environment variable to configure the `JIRA_PROJECT_ID` was removed (93066aa206d61d1ccec3e5c813a35d57bcfc43e5) because we thought it didn't have a use case as fields are linked to the project (so a change on the project means a change in the code anyways). We realized the jira project id can change without changing its fields, so for these cases it would be useful to keep having a way of configuring the jira project id.
> Update OBS jira project id and roll back way of setting it

- CHANGELOG.rst
- manager/ui_framework/fixtures/initial_data_summit.json
This PR adds two new CSCs: `ScriptQueue:3` and `Scheduler:3` to the ui_framework summit views fixture for persistence.
> Add ScriptQueue:3 and Scheduler:3 to ASummary State View on Summit

- CHANGELOG.rst
- README.md
- manager/api/tests/test_ole.py
- manager/api/views.py
- manager/manager/utils.py
This PR adds several functions in order to allow sending the defined night summary report to a specific email address. Configurations were set to provide an user and password for sending emails through a SMTP server. Now when confirming a night report, its information will be gathered and sent to the specified email address set on `NIGHTREPORT_MAIL_ADDRESS` environment variable.
> Add mailing feature so it can be used by the Night Report

- CHANGELOG.rst
- manager/api/fixtures/initial_data_remote_summit.json
This PR edits the `manager/api/fixtures/initial_data_remote_summit.json` file in order to properly set the default LOVE configuration file. This was a missing change we just realized now when LOVE01 BM was down as the deployment was trying to access an endpoint that was not being served, hence resulting in login errors as the login feature queries this default LOVE configuration file.
> Fix API fixture to point to correct default LOVE configuration file

- CHANGELOG.rst
- manager/ui_framework/fixtures/initial_data_summit.json
This PR adds the `OCPS:101` CSC to the ASummary State View on the summit `ui_framework` fixtures.
> Add OCPS:101 to ASummary State View on Summit

- CHANGELOG.rst
- manager/requirements.txt
This PR removes some dependencies from the `manager/requirements.txt` as they were not really been used by the consumers of that file. Dependencies for documentation were removed as they are already set on `docsrc/requirements.txt` and also `flake8` was removed as it is being installed using `pre-commit` hooks.
> Remove unused dependencies

- CHANGELOG.rst
- manager/manager/utils.py
This PR removes the time loss calculation of OBS jira tickets as it was currently missleading. Two mails are sent at the end of the night, on for AuxTel and one for Simonyi, however both mails have a exact same replicate of the jira tickets list, with its time loss details. This was missleading, as time loss could apply only for one telescope and not both. However this is a complex problem which needs to be discussed, but for the moment we are just removing the time loss detail to avoid confusions.
> Remove time loss calculation from nightreport mailing

- CHANGELOG.rst
- manager/api/views.py
This PR adds a white space stripping step in the `ole_send_night_report` function in order to remove empty spaces at the beginning and end of human written fields. This will be done on the final step of a night report before being sent as an email.
> Strip white spaces from human written fields in the ole_send_night_report function

- CHANGELOG.rst
- manager/ui_framework/fixtures/initial_data_summit.json
This PR replaces the `Electrometer:1` by `Electrometer:101` and also adds the `Electrometer:102` to the Summit `ASummary State View`.
> Add Electrometer:101 and Electrometer:102 to Summit ASummary State View

- CHANGELOG.rst
- manager/ui_framework/fixtures/initial_data_summit.json
This PR add the `CBP:0` CSC to the Summit `ASummary State View`.
> Add CBP:0 to Summit ASummary State View

- CHANGELOG.rst
- manager/api/tests/test_auth_api.py
- manager/api/views.py
This PR makes a small change on the feature that authenticate users against the IPA servers. Initially this was designed to only write commanding permissions (for users in the IPA `love_ops` group) when the user haven't loged into LOVE yet, this for allowing administrators to manually remove permissions on demand as needed. However, usage has shown that most of users ask to be added to the `love_ops` group after they have logged in and also there hasn't been the need to be manually removing permissions. Hence this PR removes the conditional that prevented this to happen.
> Remove conditional on authentication views that prevented commanding permissions to be overwritten

- CHANGELOG.rst
- Jenkinsfile
This PR removes a couple stages that were used to make deployments on a development environment used by Inria, however this is not being used anymore.
> Remove deprecated deployment stages from the Jenkinsfile

- CHANGELOG.rst
- manager/subscription/routing.py
This PR fixes an issue with the websockets routing that was introduced after updating the LOVE-manager on #270. After updating the django dependency, we don't need anymore to force the prefix in base to the `FORCE_SCRIPT_NAME` setting. This is being added to the websocket path automatically now.
> Adjust websockets routing as prefix is not needed anymore

- CHANGELOG.rst
- manager/api/tests/test_jira.py
- manager/manager/utils.py
Added update_time_loss() to request jira ticket by ID, and updates the existing time_lost value adding what was given in the form to the original value from the ticket.
Called this function from jira_comment() only if 'time_lost' is provided in the request_data. 
Updated test_jira_comment() to patch this new function. 
Added test_update_time_loss.
> Accumulate Time Lost from comments sent through LOVE 

- CHANGELOG.rst
- manager/api/tests/test_jira.py
- manager/manager/utils.py
This PR fixes an issue on the `update_time_lost` method by not properly reading the time lost field from the `fields` attribute that comes on the jira ticket query. Also the time_lost field passed as argument of the function comes in string format, so that needs to be parsed to `float` too so when adding time lost the code doesn't break.
> Fix issue with update_time_lost method

- CHANGELOG.rst
- manager/api/management/commands/createusers.py
- manager/api/management/commands/tests.py
- manager/runserver.sh
This PR extends the `createusers` command to include conditionals for user creation, so if a password is not defined when calling the command, the user won't be created. This way we can make the `runserver.sh` script to not include the `cmd` user pass, so this user is not created on the production deployments.
> Remove cmd user creation for production deployments

- CHANGELOG.rst
- manager/api/tests/test_commander.py
- manager/api/views.py
This PR extends the `commander` view to arrange the identity of whom is issuing a command from the LOVE-frontend.
This is connected to a LOVE-commander PR too: https://github.com/lsst-ts/LOVE-commander/pull/74.
> Add identity to issued commands through the commander view

- CHANGELOG.rst
- manager/api/tests/test_jira.py
- manager/manager/utils.py
This PR includes updates to the `update_time_lost` functionality and adds a new test case to ensure proper handling when the `time_lost` field is `None` for jira tickets that have not set that field.
* [`manager/manager/utils.py`](diffhunk://#diff-5495c8c9a3db0b4bd6fdb5797165e55eb8f5fffd8d98911c57f65ff621f796c2L538-R539): Modified the `update_time_lost` function to handle cases where the `time_lost` field is `None` by checking the value before converting it to a float.
* [`manager/api/tests/test_jira.py`](diffhunk://#diff-251265ce41ecb04086672a260886e6b0b1a598a430d342b3654db5cb2db5b690R356-R375): Added a new test `test_update_current_time_lost_none` to verify that the `update_time_lost` function correctly updates the `time_lost` field when it is initially `None`.
> Fix issue with update_time_lost being called on jira tickets that doesn't have a time lost defined

- CHANGELOG.rst
- manager/manager/settings.py
This PR adds the `CSRF_TRUSTED_ORIGINS` django setting which define hosts to allow cross site requests (requests that don't come from the same domain). This is a security measure that django sets, but it was generating some problems as the LOVE architecture forwards requests through nginx proxies which happens to set a different origin by using `http` instead of `https`. This made requests from the UI been detected as a different origin due to been generated from an `https` origin.
I've tried changing nginx proxies (e.g. https://github.com/lsst-ts/argocd-csc/blob/main/apps/love-nginx/values-tucson-teststand.yaml#L41-L73) but other services, such as the producers relies on non secure connection (`ws` instead of `wss`) so that generated problems.
This is solved by setting the …
> Fix issue with django admin panel not accessible

- CHANGELOG.rst
- manager/ui_framework/fixtures/initial_data_base.json
- manager/ui_framework/fixtures/initial_data_tucson.json
This PR updates the `Summary State` view with the most recent CSCs and also renames it to `SummaryState2`, on TTS and BTS.
> Standardize SummaryState view on TTS and BTS.

- CHANGELOG.rst
- manager/ui_framework/fixtures/initial_data_summit.json
This PR adds the `MTM1M3TS` CSC to the `ASummaryState` view fixture on Summit.
> Add MTM1M3TS to ASummaryState view fixture on Summit.

- CHANGELOG.rst
- manager/ui_framework/fixtures/initial_data_summit.json
This PR adds the following CSCs to the ASummary State view fixture on Summit:
- LedProjector:0
- LinearStage:101
- LinearStage:102
- LinearStage:103
- LinearStage:104
These are being added under the `Simonyi Survey Telescope` > `Calibration Systems` section.
> Add LedProjector and LinearStage CSCs to ASummaryState view fixture on Summit.

- CHANGELOG.rst
- manager/api/tests/test_jira.py
- manager/manager/utils.py
This PR refactors the `get_jira_obs_report` method to account for timezones when using the JIRA REST API so we don't rely on a hardcoded date range for queries which could affect if using different users to authenticate the query and also account for daylight saving time. Tests were extended to comply with these changes.
> Refactor get_jira_obs_report method to account for JIRA REST API user timezone.

- CHANGELOG.rst
- manager/ui_framework/fixtures/initial_data_base.json
- manager/ui_framework/fixtures/initial_data_tucson.json
This PR renames the Summary State views on TTS and BTS to `SummaryState`. Also recently added CSCs to TTS were included on this view. The following CSCs were added to the TTS `SummaryState` view: `DREAM`, `EAS`, `OCPS:101`, `CBP`, `LEDProjector`, `LinearStage[101,202,103,104]`, `Electrometer[101,102,201]` and `ATBuilding`.
> Make the SummaryState view as the official one for TTS and BTS.

- CHANGELOG.rst
- manager/manager/utils.py
This PR extends the `jira_ticket` utility function to send errors details that comes from querying the JIRA REST API.
This PR is related to: https://github.com/lsst-ts/LOVE-frontend/pull/678.
> Show error details from queries to the JIRA REST API.

- CHANGELOG.rst
- manager/ui_framework/fixtures/initial_data_summit.json
This PR adds the new `EAS:0` CSC to the `ASummary State` view on Summit.
> Add EAS:0 CSC to summit ASummary State view on Summit.

- CHANGELOG.rst
- manager/manager/settings.py
This PR adjusts the django settings to be able to configure the channels `group_expiry` through an environment variable.
> Make channels layer group expiry parameter configurable through an environment variable.

- CHANGELOG.rst
- manager/ui_framework/fixtures/initial_data_base.json
This PR adds the following list of CSCs to the SummaryState view on BTS:
- ATBuilding
- DREAM
- EAS
- LEDProjector
- LinearStage:[101,102,103,104]
- CBP, Electrometer:[101,102,201]
- OCPS:101
> Add recently added CSCs to SummaryState view on BTS.

- CHANGELOG.rst
- manager/api/tests/test_ole.py
- manager/api/views.py
- manager/manager/utils.py
This PR adds a conversion for dates that comes in UTC scale and need to be converted to TAI to comply with the narrativelog REST API definitions. This PR is related to: https://github.com/lsst-ts/LOVE-frontend/pull/681.
> Convert narrativelog date_begin and date_end UTC datetimes to TAI.

- CHANGELOG.rst
- manager/api/tests/test_jira.py
- manager/api/tests/test_ole.py
- manager/api/views.py
- manager/manager/utils.py
This PR refactors the jira_ticket method to comply with the new OBS systems hierarchy:
- Adjusted the narrativelog view to parse the new `components_json` field which comes in json format.
- Remove the components setting for creating jira tickets.
- Refactored tests to comply with the new hierarchy.
> Refactor jira_ticket method to comply with new OBS systems hierarchy.

- CHANGELOG.rst
- manager/manager/utils.py
This PR removes the `labels` parameter from the payload for Jira tickets creation on the `jira_ticket` method. The param is not used anymore for ticket creation.
> Remove labels param from payload on jira_ticket method.

- CHANGELOG.rst
- manager/ui_framework/fixtures/initial_data_summit.json
This PR adds the `Simonyi Monitor` view to the ui-framework summit fixtures in order to persist the respective view.
> Add Simonyi Monitor view to ui-framework summit fixtures.

- CHANGELOG.rst
- manager/ui_framework/fixtures/initial_data_summit.json
This PR updates the `ASummary State` view on the `ui-framework` fixtures for summit. New CSCs were added to the `Simonyi Survey Telescope / Calibration Systems` section:
* FiberSpectrograph:101
* FiberSpectrograph:102
* Electrometer:103
> Add new CSCs to the ASummary State view on summit.

- CHANGELOG.rst
- manager/ui_framework/fixtures/initial_data_summit.json
This PR updates the `ASummary State` view on the `ui-framework` fixtures for summit. New CSCs were added:
- `Observatory / Environment / DREAM`
- `ATCS / Support & Monitoring / ATBuilding`
> Add DREAM and ATBuilding CSCs to ASummary State view on summit.

- CHANGELOG.rst
- manager/ui_framework/fixtures/initial_data_base.json
- manager/ui_framework/fixtures/initial_data_summit.json
This PR adds new ESS CSCs to the `ui-framework` fictures for summit and base:
- `Observatory / Environment / ESS:304` -> summit + base
- `Observatory / Environment / ESS:305` -> summit + base
- `Observatory / Environment / ESS:306 ` -> summit + base
- `Observatory / HigherLevel / OCPS:3 ` -> summit
> Add new CSCs to summary state views: ess-ringss, ess-electric-generators and lsstcam-ocps.

- CHANGELOG.rst
- manager/api/fixtures/initial_data_remote_base.json
- manager/api/fixtures/initial_data_remote_summit.json
- manager/api/fixtures/initial_data_remote_tucson.json
This PR updates the `api` fixtures for `remote_summit`, `remote_base` and `remote_tucson` in order to include new LOVE config files: `no-alarms.json` and `all-alarms.json`. These new config files will be stored through the source code, check https://github.com/lsst-sqre/phalanx/pull/4465 for more details.
> Add LOVE config files references to ui-framework remote fixtures for summit, base and tucson.

- CHANGELOG.rst
- manager/ui_framework/fixtures/initial_data_base.json
This PR adds the `Electrometer:103` CSC to the `ui-framework` fixture for base on the `Simonyi Survey Telescope / Calibration Systems` section.
> Add Electrometer:103 to SummaryState view on BTS.

- CHANGELOG.rst
- README.md
- manager/api/management/commands/createusers.py
- manager/api/management/commands/tests.py
- manager/runserver.sh
This PR adds three new users to the `createusers` command:
- `base_control_room`
- `tucson_control_room`
- `slac_control_room`
In adition to the RSP Summit 1password vault, passwords for these users are also stored in the Operators 1password vault.
> Add remote control rooms read-only users for LOVE summit monitoring.

- CHANGELOG.rst
- manager/api/fixtures/initial_data_remote_base.json
- manager/api/fixtures/initial_data_remote_summit.json
- manager/api/fixtures/initial_data_remote_tucson.json
This PR updates the `api` fixtures for `remote_summit`, `remote_base` and `remote_tucson` in order to add a `serious-alarms.json` LOVE config file as the all alarms one is the default one now.
See also https://github.com/lsst-sqre/phalanx/pull/4546 for more details.
> Add serious alarms config file reference to ui-framework remote fixtures for summit, base and tucson.

- CHANGELOG.rst
- manager/ui_framework/fixtures/initial_data_base.json
- manager/ui_framework/fixtures/initial_data_summit.json
This PR adds new ESS CSCs: 114, 115, 116 and 117 to the Summit and BTS `ui-framework` fixtures on the `Observatory / Environment` section.
> Add new ESS 114, 115, 116 and 116 for M1M3 thermal scanners to Summit and BTS.

- CHANGELOG.rst
- manager/ui_framework/fixtures/initial_data_base.json
- manager/ui_framework/fixtures/initial_data_summit.json
This PR adds new CSCs to the BTS and Summit `ui-framework` fixtures:
- `Observatory / Environment / ESS:2`.
- `Simonyi Survey Telescope / Calibration Systems / MTReflector`.
> Add ESS:2 and MTReflector to sumary state views on BTS and Summit.

- CHANGELOG.rst
- manager/ui_framework/fixtures/initial_data_base.json
- manager/ui_framework/fixtures/initial_data_summit.json
- manager/ui_framework/fixtures/initial_data_tucson.json
This PR adds new CSCs to the Summit, BTS and TTS `ui-framework` fixtures:
- `Observatory / Environment / ESS:118`.
- `Observatory / Environment / ESS:119`.
- `Observatory / Environment / ESS:120`.
> Add new ESS 118, 119 and 120 to ui-framework fixtures on summit, base and tucson.

- CHANGELOG.rst
- manager/api/management/commands/createusers.py
- manager/api/tests/test_jira.py
- manager/api/tests/test_ole.py
- manager/api/urls.py
- manager/api/views.py
- manager/manager/utils.py
This PR adds new api endpoints:
- `efd/top_timeseries`: to retrieve most recent timeseries (see https://github.com/lsst-ts/LOVE-commander/pull/79).
- `jira/report/<project>/`: to retrieve a list of Jira tickets for a specified day obs, currently only supporting OBS project queries.
It also updates respective code to the Nightreport API to support the new LOVE nightlog v2, see https://github.com/lsst-ts/LOVE-frontend/pull/718.
> Add Jira tickets and EFD most recent timeseries query endpoints.

- CHANGELOG.rst
- manager/ui_framework/fixtures/initial_data_summit.json
This PR removes the `ComCam`  and `Star Tracker` sections from the `Simonyi Survey Telescope` group in the ASummary State View from Summit `ui-framework` fixture.
> Remove ComCam and Star Tracker subsections from the Simonyi Survey Telescope group in the ASummary State View at summit.

- CHANGELOG.rst
- manager/ui_framework/fixtures/initial_data_base.json
- manager/ui_framework/fixtures/initial_data_tucson.json
This PR adds the HVAC CSCs to the BTS and TTS ui-framework fixtures: `Observatory / Environment / HVAC`.
> Add HVAC to ui-framework fixtures on base and tucson.

- CHANGELOG.rst
- manager/api/tests/test_jira.py
- manager/manager/utils.py
This PR fixes the Jira API interface used to retrieve OBS tickets. The old jql query method was [marked for deprecation the 31th of October of 2024](https://developer.atlassian.com/changelog/#CHANGE-2046), but got finally removed during these days (week of the 15th of September 2025). The fix was a slight adjustments to query the `jql` endpoint plus specifying the fields we want to  retrieve.
> Fix deprecated jql Jira interface.
